# settings
baseurl: ""
url: "https://gionn.net"

# meta
title: gionn.net
author: Giovanni Toraldo
description: A blog about tech, programming and my personal life, alive and kicking since 2005.

# social links
twitter_username: gionn
github_username:  gionn
facebook_username: gionn
instagram_username: gionn_net
linkedin_username: giovannitoraldo
rss: rss

# integrations
disqus:
  shortname: gionn-blog

# others
paginate: 5
permalink: /:year/:month/:day/:title/
timezone: Europe/Rome

theme: jekyll-theme-hydeout
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
