# Site settings
title: gionn.net
author: Giovanni Toraldo
email: me@gionn.net
description: Open-Source enthusiast with SuperCow Powers, a PHP/Java/whatever developer, devops, writer of the OpenNebula book.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gionn.net" # the base hostname & protocol for your site
twitter_username: gionn
github_username:  gionn

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/
paginate: 5
timezone: Europe/Rome

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
