name: pre-commit

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install image optimization tools
        run: |
          sudo apt-get update -q
          sudo apt-get install -y jpegoptim optipng
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@6d82a126f5f8b2cbfe2663c2c6c4fa3dbd5bdc7e # v18.15.0
        with:
          python-version: '3.13.3'
